### ISSUE TITLE
add first todo

### ISSUE THREAD

**Issue by MohammadJS2642** [MohammadJS2642/TodoApp#3]
- [x] navigation 
- [x] Add Todo Name 
- [ ] textfield
- [ ] list of todo items
- [ ] Save button in app bar 
- [ ] after save navigate to main page
- [ ] in main page must show list of todo list 
- [ ] user clicked on todo list must be see items in todo
